name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject environment variables into config.json
      run: |
        echo "{ \"API_KEY\": \"${{ secrets.API_KEY }}\", \"SHEET_ID\": \"${{ secrets.SHEET_ID }}\" }" > config.json

    - name: Deploy (optional)
      run: echo "Deployment steps here" # Customize deployment as needed
